### ISSUE TITLE
Remove Requirement for `rb-appscript`

### ISSUE THREAD

**Issue by BrendanThompson** [ttscoff/OTask#13]
Would it be possible to remove the requirement for `rb-appscript` as there seem to be issues with installing it under Yosemite.

**Comment by zenspider** [comment]
No, it's not possible.

**Comment by BrendanThompson** [comment]
By remove the requirement I mean replace it with something other than `rb-appscript`

**Comment by loranallensmith** [comment]
Hey @BrendanThompson and @zenspider! :wave:  Just wanted to ping back on this issue to let you know #15 replaced the `rb-appscript` dependency for this project with a different gem (`rb-scpt`).  This resolved build errors I was encountering, so it may resolve your installation issues.

The newest version of the code hasn't landed on rubygems.org yet, but you can build and install it locally from the source in this repository.  I dropped some quick steps into [this gist](https://gist.github.com/loranallensmith/b9a23a08b5b178347a6828c02d6bcc6d) in case they're helpful at all.

**Comment by BrendanThompson** [comment]
Hey @loranallensmith, I built [rb-scpt](https://github.com/BrendanThompson/rb-scpt) to fix this issue :)
